import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Dados dos condomínios extraídos do Excel
const condominiosData = [
  { type: "APARTAMENTO", name: "Tamboré 1" },
  { type: "CASA", name: "Sua Cidade 0" },
  { type: "CASA", name: "Sua Cidade 1" },
  { type: "CASA", name: "Sua Cidade 2" },
  { type: "CASA", name: "Sua Cidade 3" },
  { type: "CASA", name: "Sua Cidade 4" },
  { type: "CASA", name: "Sua Cidade 5" },
  { type: "CASA", name: "Sua Cidade 6" },
  { type: "CASA", name: "Sua Cidade 7" },
  { type: "CASA", name: "Sua Cidade 9" },
  { type: "CASA", name: "Sua Cidade 10" },
  { type: "CASA", name: "Sua Cidade 11" },
  { type: "CASA", name: "Sua Cidade 12" },
  { type: "CASA", name: "Gênesis 1" },
  { type: "CASA", name: "Gênesis 2" },
  { type: "CASA", name: "Tamboré 1" },
  { type: "CASA", name: "Tamboré 2" },
  { type: "CASA", name: "Tamboré 5" },
  { type: "CASA", name: "Tamboré 6" },
  { type: "CASA", name: "Tamboré 7" },
  { type: "CASA", name: "Tamboré 10" },
  { type: "CASA", name: "Tamboré 11" },
  { type: "TERRENO", name: "Melville" },
  { type: "APARTAMENTO", name: "Splendya 2" },
  { type: "APARTAMENTO", name: "Lorian Boulevard" },
  { type: "APARTAMENTO", name: "Panamby" },
  { type: "APARTAMENTO", name: "Parque Tamboré 1" },
  { type: "APARTAMENTO", name: "Parque Tamboré 2" },
  { type: "APARTAMENTO", name: "Parque Tamboré 3" },
  { type: "APARTAMENTO", name: "Parque Tamboré 4" },
  { type: "APARTAMENTO", name: "Parque Tamboré 5" },
  { type: "APARTAMENTO", name: "Parque Tamboré 6" },
  { type: "APARTAMENTO", name: "Parque Tamboré 7" },
  { type: "APARTAMENTO", name: "Parque Tamboré 8" },
  { type: "APARTAMENTO", name: "Parque Tamboré 9" },
  { type: "APARTAMENTO", name: "Parque Tamboré 10" },
  { type: "APARTAMENTO", name: "Parque Tamboré 11" },
  { type: "APARTAMENTO", name: "Parque Tamboré 12" },
  { type: "APARTAMENTO", name: "Parque Tamboré 13" },
  { type: "APARTAMENTO", name: "Parque Tamboré 14" },
  { type: "APARTAMENTO", name: "Parque Tamboré 15" },
  { type: "APARTAMENTO", name: "Parque Tamboré 16" },
  { type: "APARTAMENTO", name: "Parque Tamboré 17" },
  { type: "APARTAMENTO", name: "Parque Tamboré 18" },
  { type: "APARTAMENTO", name: "Parque Tamboré 19" },
  { type: "APARTAMENTO", name: "Parque Tamboré 20" },
  { type: "APARTAMENTO", name: "Parque Tamboré 21" },
  { type: "APARTAMENTO", name: "Parque Tamboré 22" },
  { type: "APARTAMENTO", name: "Parque Tamboré 23" },
  { type: "APARTAMENTO", name: "Parque Tamboré 24" },
  { type: "APARTAMENTO", name: "Parque Tamboré 25" },
  { type: "APARTAMENTO", name: "Parque Tamboré 26" },
  { type: "APARTAMENTO", name: "Parque Tamboré 27" },
  { type: "APARTAMENTO", name: "Parque Tamboré 28" },
  { type: "APARTAMENTO", name: "Parque Tamboré 29" },
  { type: "APARTAMENTO", name: "Parque Tamboré 30" },
  { type: "APARTAMENTO", name: "Neo" },
  { type: "CASA", name: "Burle Marx" },
  { type: "APARTAMENTO", name: "Alpha Gran" },
  { type: "TERRENO", name: "Campos do Conde" },
  { type: "APARTAMENTO", name: "Level" },
  { type: "APARTAMENTO", name: "Bellagio" },
  { type: "APARTAMENTO", name: "Essencia Sua Cidade" },
  { type: "APARTAMENTO", name: "Vogue" },
  { type: "APARTAMENTO", name: "Californian Towers" },
  { type: "APARTAMENTO", name: "Parque Tamboré" },
  { type: "APARTAMENTO", name: "Choice" },
  { type: "CASA", name: "Alpha Conde" },
  { type: "CASA", name: "Vista Alta" },
  { type: "APARTAMENTO", name: "Eredita" },
  { type: "APARTAMENTO", name: "Paisagem Tamboré" },
  { type: "APARTAMENTO", name: "Top Village" },
  { type: "APARTAMENTO", name: "Win" },
  { type: "APARTAMENTO", name: "Premium Tamboré" },
  { type: "APARTAMENTO", name: "Ápice Park" },
  { type: "APARTAMENTO", name: "Terraços Tamboré" },
  { type: "APARTAMENTO", name: "Master" },
  { type: "CASA", name: "Tamboré 3" },
  { type: "APARTAMENTO", name: "Alpha Towers" },
  { type: "CASA", name: "Alphasítio" },
  { type: "APARTAMENTO", name: "Resort Tamboré" },
  { type: "APARTAMENTO", name: "Alpha Vita" },
  { type: "APARTAMENTO", name: "Igloo" },
  { type: "APARTAMENTO", name: "Cauaxi Plaza" },
  { type: "APARTAMENTO", name: "Glass" },
  { type: "APARTAMENTO", name: "Ghaia" },
  { type: "COMERCIAL", name: "Brascan" },
  { type: "APARTAMENTO", name: "Garden Hill" },
  { type: "APARTAMENTO", name: "Parc Athenee" },
  { type: "CASA", name: "Alpha Plus" },
  { type: "APARTAMENTO", name: "Reserva Alphasítio" },
  { type: "APARTAMENTO", name: "Link Studios" },
  { type: "APARTAMENTO", name: "KAA Home" },
  { type: "APARTAMENTO", name: "On The Park" },
  { type: "APARTAMENTO", name: "Europa" },
  { type: "CASA", name: "Valville 2" },
  { type: "APARTAMENTO", name: "Concorde" },
  { type: "APARTAMENTO", name: "Residencial Alphalife" },
  { type: "APARTAMENTO", name: "Bonnard 307" },
  { type: "APARTAMENTO", name: "Alpha Club" },
  { type: "COMERCIAL", name: "Centro Empresarial Araguaia" },
  { type: "APARTAMENTO", name: "Splendya 1" },
  { type: "APARTAMENTO", name: "Beat" },
  { type: "APARTAMENTO", name: "Canvas High Houses" },
  { type: "APARTAMENTO", name: "Soho" },
  { type: "APARTAMENTO", name: "Jardins de Monet" },
  { type: "APARTAMENTO", name: "Bosques de Tamboré" },
  { type: "APARTAMENTO", name: "Chateau" },
  { type: "APARTAMENTO", name: "The Garden" },
  { type: "CASA", name: "18 do Forte" },
  { type: "APARTAMENTO", name: "Saint Paul" },
  { type: "COMERCIAL", name: "West Gate" },
  { type: "APARTAMENTO", name: "One Gramercy" },
  { type: "APARTAMENTO", name: "Panoramic" },
  { type: "CASA", name: "Scenic" },
  { type: "APARTAMENTO", name: "Classic" },
  { type: "APARTAMENTO", name: "Oiapoque" },
  { type: "APARTAMENTO", name: "Columbia" },
  { type: "APARTAMENTO", name: "Acqua Park" },
  { type: "APARTAMENTO", name: "Paratii" },
  { type: "CASA", name: "Vila Velha" },
  { type: "APARTAMENTO", name: "Saint Thomas" },
  { type: "APARTAMENTO", name: "Myra" },
  { type: "APARTAMENTO", name: "The Lake" },
  { type: "APARTAMENTO", name: "Central Park" },
  { type: "APARTAMENTO", name: "The Penthouses Tamboré" },
  { type: "APARTAMENTO", name: "Vision" },
  { type: "APARTAMENTO", name: "Alphama" },
  { type: "APARTAMENTO", name: "Grand Floridian" },
  { type: "APARTAMENTO", name: "Lotus" },
  { type: "CASA", name: "Conde II" },
  { type: "APARTAMENTO", name: "De Ville" },
  { type: "APARTAMENTO", name: "Gran Sua Cidade" },
  { type: "APARTAMENTO", name: "Fiori" },
  { type: "APARTAMENTO", name: "Sol Sua Cidade" },
  { type: "APARTAMENTO", name: "Edifício Alphalife" },
  { type: "APARTAMENTO", name: "Itapecuru" },
  { type: "APARTAMENTO", name: "Edifício Phanton" },
  { type: "APARTAMENTO", name: "Copacabana" },
  { type: "CASA", name: "Origem" },
  { type: "APARTAMENTO", name: "Ekko Live" },
  { type: "APARTAMENTO", name: "America 1" },
  { type: "APARTAMENTO", name: "Duplex House" },
  { type: "COMERCIAL", name: "New Worker Tower" },
  { type: "COMERCIAL", name: "Quebec" },
  { type: "APARTAMENTO", name: "Sunset Itapecuru" },
  { type: "APARTAMENTO", name: "Alpha Life" },
  { type: "CASA", name: "Oasis" },
  { type: "COMERCIAL", name: "Alpha Green" },
  { type: "APARTAMENTO", name: "Stadium Corporate" },
  { type: "COMERCIAL", name: "Office Grajau" },
  { type: "APARTAMENTO", name: "America 2" },
  { type: "APARTAMENTO", name: "Verte Ville" },
  { type: "COMERCIAL", name: "Edifício Eagle Point" },
  { type: "COMERCIAL", name: "Centro de apoio 2" },
  { type: "APARTAMENTO", name: "Único Sua Cidade" },
  { type: "APARTAMENTO", name: "Hit" },
  { type: "APARTAMENTO", name: "Verone" },
  { type: "APARTAMENTO", name: "Village" },
  { type: "APARTAMENTO", name: "Iakatu" },
  { type: "APARTAMENTO", name: "Artesano" },
  { type: "APARTAMENTO", name: "Wi House" },
  { type: "APARTAMENTO", name: "Monte Carlo" },
  { type: "CASA", name: "Sua Cidade 8" },
  { type: "COMERCIAL", name: "Smart Office" },
  { type: "APARTAMENTO", name: "Parque Barueri" },
  { type: "APARTAMENTO", name: "Quality Hotel" },
  { type: "APARTAMENTO", name: "Alto Da Mata" },
  { type: "COMERCIAL", name: "Gama Offices" },
  { type: "COMERCIAL", name: "Alpha Offices" },
  { type: "COMERCIAL", name: "Link offices" },
  { type: "APARTAMENTO", name: "Comfort suítes" },
  { type: "COMERCIAL", name: "Shopping Service" },
  { type: "COMERCIAL", name: "Edifício Montreal" },
  { type: "COMERCIAL", name: "Medic Life" },
  { type: "APARTAMENTO", name: "Regina" },
  { type: "APARTAMENTO", name: "Flat Sequóia" },
  { type: "APARTAMENTO", name: "Fatto" },
  { type: "CASA", name: "Uptown Housing" },
  { type: "APARTAMENTO", name: "Sequóia" },
  { type: "APARTAMENTO", name: "Reserva do Alto" },
  { type: "APARTAMENTO", name: "Le Bougainville" },
  { type: "APARTAMENTO", name: "Loft" },
  { type: "APARTAMENTO", name: "Victoria 2" },
  { type: "APARTAMENTO", name: "Discovery" },
  { type: "APARTAMENTO", name: "Alpha Stay" },
  { type: "COMERCIAL", name: "Metropolis" },
  { type: "APARTAMENTO", name: "Pacific Towers" },
  { type: "APARTAMENTO", name: "Letoile" },
  { type: "APARTAMENTO", name: "Victoria 1" },
  { type: "APARTAMENTO", name: "Ana Paula" },
  { type: "APARTAMENTO", name: "Manhattan" },
  { type: "COMERCIAL", name: "Pravda" },
  { type: "COMERCIAL", name: "Centro Administrativo Rio Negro" },
  { type: "APARTAMENTO", name: "Infinity" },
  { type: "APARTAMENTO", name: "Granville" },
  { type: "APARTAMENTO", name: "Blue Tree" },
  { type: "APARTAMENTO", name: "Cauaxi Empresarial" },
  { type: "TERRENO", name: "Polo Industrial Tamboré" },
  { type: "COMERCIAL", name: "Alpha Premium" },
  { type: "COMERCIAL", name: "Complexo Madeira" },
  { type: "CASA", name: "New Ville" },
  { type: "APARTAMENTO", name: "Trend Tower" },
  { type: "COMERCIAL", name: "Personal Business Office" },
  { type: "APARTAMENTO", name: "Marte" },
  { type: "COMERCIAL", name: "Alfacon" },
  { type: "COMERCIAL", name: "Guinzza Trade Center" },
  { type: "COMERCIAL", name: "Murano" },
  { type: "APARTAMENTO", name: "Monaco" },
  { type: "COMERCIAL", name: "Plaza" },
  { type: "APARTAMENTO", name: "Bourbon" },
  { type: "APARTAMENTO", name: "San Francisco" },
  { type: "APARTAMENTO", name: "Alphaview" },
  { type: "CASA", name: "Morada dos Pássaros" },
  { type: "APARTAMENTO", name: "Selenita" },
  { type: "COMERCIAL", name: "West Towers" },
  { type: "CASA", name: "Taruma" },
  { type: "COMERCIAL", name: "West Side" },
  { type: "CASA", name: "Morada das Flores" },
];

export async function POST(request: NextRequest) {
  try {
    let imported = 0;
    let errors = 0;

    for (const condo of condominiosData) {
      try {
        // Verificar se já existe
        const existing = await prisma.condominium.findFirst({
          where: { name: condo.name },
        });

        if (existing) {
          continue; // Pular se já existe
        }

        // Gerar slug
        const slug = condo.name
          .toLowerCase()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/(^-|-$)/g, "");

        // Definir tipologias baseado no tipo
        const hasApartment = condo.type === "APARTAMENTO";
        const hasHouse = condo.type === "CASA";
        const hasTerrain = condo.type === "TERRENO";
        const hasCommercial = condo.type === "COMERCIAL";

        await prisma.condominium.create({
          data: {
            name: condo.name,
            slug,
            type: condo.type as any,
            city: "Santana de Parnaíba",
            state: "SP",
            neighborhood: "Sua Cidade",
            hasApartment,
            hasHouse,
            hasTerrain,
            hasCommercial,
            isActive: true,
          },
        });

        imported++;
      } catch (err) {
        console.error(`Erro ao importar ${condo.name}:`, err);
        errors++;
      }
    }

    return NextResponse.json({ imported, errors, total: condominiosData.length });
  } catch (error) {
    console.error("Erro na importação:", error);
    return NextResponse.json({ error: "Erro na importação" }, { status: 500 });
  }
}
